### ISSUE TITLE
Request to add *.Portable.dll assemblies

### ISSUE THREAD

**Issue by umamimolecule** [SimonCropp/Alt.SharePoint.Client#13]
Hello,

I have a .Net core app which references the `*.Portable.dll` versions of the assemblies, [as mentioned here](https://rajujoseph.com/getting-net-core-and-sharepoint-csom-play-nice/).

Would it be possible for you to add converted versions of these assemblies?

Thanks!

**Comment by SimonCropp** [comment]
sorry i missed this one. it is still a problem? your link is broken

**Comment by umamimolecule** [comment]
Hey, for me personally it's no longer an issues as I have patched the relevant DLL's myself.

Here's another link which hopefully describes how get a .Net Core application working with CSOM: https://sakarih.wordpress.com/2019/05/15/sharepoint-online-client-object-model-and-net-core/

**Comment by SimonCropp** [comment]
@umamimolecule if you still need this, i am happy to accept a PR
